name: docs_maker Application CI

on:
  push:
    branches:
      - main
      - 'f/**'
      - 't/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Unittest:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute unit test
        run: |
          python3 -m pytest tests -v

  Quality:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run flake8 docs_maker
        run: |
           flake8 --ignore E501 docs_maker

      - name: Run flake8 docs_maker_gui
        run: |
          flake8 --ignore E501 --exclude docs_maker_main_window.py,resources.py docs_maker_gui

      - name: Run mypy docs_maker
        run: |
          mypy docs_maker

      - name: Run mypy docs_maker_gui
        run: |
          mypy docs_maker_gui
          
  Publish:
    runs-on: self-hosted
    needs:
      - unittest
      - quality
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Build package
        uses: actions/checkout@v3

      - name: Get version from tag
        run: |
          TAG="${{ github.ref }}"
          TAG=${TAG#refs/tags/}
          poetry version $TAG

      - name: Check pyproject.toml
        run: |
          cat pyproject.toml

      - name: Publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build
