name: docs_maker Application CI

on:
  push:
    branches:
      - main
      - 'f/**'
      - 't/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  unittest:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install docs_maker for unit test
        run: |
          pip3 install .

      - name: Execute unit test
        run: |
          pytest

  build:
    runs-on: self-hosted
    needs: unittest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Build package
        uses: actions/checkout@v3

      - name: Get version from tag
        run: |
          TAG="${{ github.ref }}"
          TAG=${TAG#refs/tags/}
          poetry version $TAG

      - name: Check pyproject.toml
        run: |
          cat pyproject.toml

      - name: Publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run job 1
        run: echo "Running job 1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run job 2
        run: echo "Running job 2"

  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run job 3
        run: echo "Running job 3"
